# Add classes to this list
# Every class in this list needs to have classname and from_json()
# See app/helpers/json_util.py for more information
CLASS_NAMES = [
    'OHLC',
    'Order',
    'KrakenOrder',
    'Exchange',
    'KrakenExchange',
    'CoinbaseExchange',
    'RobinhoodCryptoExchange',
    'RequestConfig',
    'ExchangeConfig',
    'CoinMarketCapAPI',
    'Bot',
    'StrategyConfig',
    'Strategy',
    'LSTMStrategy',
    'RiskManager',
    'RiskManagerConfig',
    'Position',
    'PositionManager',
    'BotConfig',
    'FuturesExchange',
    'KrakenFuturesExchange',
    'TestExchange',
    'TestStrategy',
    'BinanceExchange',
    'BinanceUSExchange',
]